const days=[
{d:"01",date:"10/03",city:"ISTANBUL",theme:"Arrival & Golden Horn Night",stay:"Golden City Hotel Istanbul",events:[["16:10 / 19:40","pkg","이스탄불 도착 · 여행사 픽업","OZ551 또는 KE955 도착 후 인솔자 미팅. 숙소 이동."],["저녁","free","첫날 자유일정 후보","장거리 비행 후 무리하지 않는 코스. 숙소 주변 갈라타 · 카라쾨이 · 갈라타교 야경을 우선 후보로 제시.","갈라타 일대|카라쾨이|갈라타교 야경"],["식사","free","저녁 후보","도착 시각에 따라 숙소 주변에서 선택. Mehmet Usta는 고등어 Balık Dürüm 후보.","",[["Sokak Lezzeti Tarihi Balık Dürümcü Mehmet Usta","https://maps.app.goo.gl/iYXYBfUhTFFQ7ooJ8","4.3 · 4,100+","Balık Dürüm · 생선랩","₺200–400","토 11:00–00:30"],["Fiyort Karaköy","https://www.google.com/maps/search/?api=1&query=Fiyort+Karakoy+Istanbul","","터키·세계요리","₺₺–₺₺₺","호텔 10층 · 도착일 편의성"]]]]},
{d:"02",date:"10/04",city:"ANTALYA",theme:"Old Town & Mediterranean",stay:"Start Otel",events:[["09:00","pkg","공항 이동","여행사 차량으로 공항 이동."],["12:00–13:20","pkg","이스탄불 → 안탈리아","PC2008 · 위탁수하물 15kg."],["오후","free","안탈리아 자유일정 후보","Start Otel과 칼레이치 접근성을 고려한 도보 중심 후보. 조원 의견수렴 후 확정.","하드리아누스 문|칼레이치 골목|구항구|흐드르륵 탑"],["저녁","free","칼레이치 저녁 후보","관광 동선 안에서 Google 평점과 리뷰 수가 안정적인 곳 위주.","",[["Balıkçı Meyhanesi Kaleiçi","https://www.google.com/maps/search/?api=1&query=Balikci+Meyhanesi+Kaleici","4.8 · 5,600+","해산물 · 메제","₺₺₺","11:00–01:00"],["Chiaro Garden Fish & Steak","https://www.google.com/maps/search/?api=1&query=Chiaro+Garden+Fish+Steak+Antalya","4.9 · 700+","생선 · 스테이크","₺800–2,000","12:00–23:55"],["Old Town Restaurant 07","https://www.google.com/maps/search/?api=1&query=Old+Town+Restaurant+07+Antalya","4.5 · 3,800+","터키·지중해식","₺400–1,400","10:00–01:00"]]]]},
{d:"03",date:"10/05",city:"PAMUKKALE",theme:"Travertines & Ancient Spa City",stay:"Start Otel · Antalya",events:[["08:00","pkg","숙소 출발","파묵칼레 투어 전용차량."],["12:00–15:00","pkg","파묵칼레 + 히에라폴리스","여행사 투어에 포함된 핵심 일정. 흰 석회붕과 고대 온천도시를 같은 방문권역에서 관람.","파묵칼레 석회붕|히에라폴리스 고대도시"],["19:00","pkg","안탈리아 숙소 복귀","투어 종료 후 Start Otel 복귀."]]},
{d:"04",date:"10/06",city:"ANTALYA → CAPPADOCIA",theme:"Slow Morning, Cave Town Evening",stay:"Cappadocia Caves Hotel",events:[["오전","free","안탈리아 오전 자유시간","10/4에 못 본 칼레이치 후보 또는 카페·산책 위주. 13시 공항 이동을 고려해 먼 곳은 제외.","칼레이치 재방문|카페·브런치|짧은 쇼핑"],["13:00","pkg","공항 이동","여행사 차량."],["16:05–17:15","pkg","안탈리아 → 카파도키아","PC4322 · 위탁수하물 15kg."],["저녁","free","괴레메 산책 + 저녁 후보","체크인 후 괴레메 중심에서 식사.","",[["WOOD FIRE BARBEQUE","https://www.google.com/maps/search/?api=1&query=WOOD+FIRE+BARBEQUE+Goreme","4.8 · 5,100+","바비큐 · 터키식","₺₺","10:30–23:00"],["Göreme Han Restaurant","https://www.google.com/maps/search/?api=1&query=Goreme+Han+Restaurant","4.7 · 2,900+","터키 가정식","₺₺","10:00–22:00"],["Cava Restaurant","https://www.google.com/maps/search/?api=1&query=Cava+Restaurant+Goreme","4.9 · 300+","터키·퓨전","₺₺–₺₺₺","07:30–01:00"]]]]},
{d:"05",date:"10/07",city:"CAPPADOCIA",theme:"Balloon & Red Route",stay:"Cappadocia Caves Hotel",events:[["새벽","free","열기구 투어 (선택)","기상과 예약 상황에 따라 진행. 10/9도 선택 가능일."],["낮","free","레드투어 추천 코스","여행사 홈페이지의 레드투어 코스를 자유일정 후보로 제시. 아직 확정 전.","괴레메 파노라마|요정의 굴뚝|아바노스 마을|우치히사르 성"],["저녁","free","괴레메 저녁 후보","레드루트 종료 후 숙소 복귀 동선을 고려.","",[["Sedef","https://www.google.com/maps/search/?api=1&query=Sedef+Restaurant+Goreme","4.6 · 10,000+","터키요리 · 케밥","₺₺","09:30–01:00"],["Gurme Kebab Restaurant","https://www.google.com/maps/search/?api=1&query=Gurme+Kebab+Restaurant+Goreme","4.7 · 6,800+","케밥","₺₺","09:00–23:30"],["NANA Cappadocia","https://www.google.com/maps/search/?api=1&query=NANA+Cappadocia","4.9 · 300+","터키요리 · 루프탑","₺₺–₺₺₺","08:00–23:00"]]]]},
{d:"06",date:"10/08",city:"CAPPADOCIA",theme:"Green Route · Underground & Valley",stay:"Cappadocia Caves Hotel",events:[["09:00","pkg","그린투어 출발","여행사 전용차량."],["낮","pkg","그린투어","데린쿠유 지하도시 → 으흘라라 계곡 → 셀리메 수도원 → 전망대.","데린쿠유 지하도시|으흘라라 계곡|셀리메 수도원|전망대"],["18:00","pkg","숙소 도착","투어 종료."],["저녁","free","괴레메 자유 저녁","컨디션에 따라 전날 후보 중 미방문 식당 또는 숙소 주변 식사."]]},
{d:"07",date:"10/09",city:"ISTANBUL",theme:"Historic Peninsula · Candidate Evening",stay:"Csk The Halich Port İstanbul",events:[["11:00","pkg","공항 이동","카파도키아 숙소 출발."],["13:10–14:35","pkg","카파도키아 → 이스탄불","PC2735 · 위탁수하물 15kg."],["오후·저녁","free","이스탄불 자유일정 후보","호텔 체크인 후 역사반도와 골든혼권 후보. 10/10 오전과 나눠 조원 투표 후 확정.","스파이스 바자르|에미뇌|술탄아흐메트 광장 야경|갈라타·카라쾨이"],["저녁","free","식사 후보","선택 동선 확정 후 2~3곳으로 최종 재선정. Mehmet Usta는 카라쾨이 선택 시 다시 후보로 사용 가능."]]},
{d:"08",date:"10/10",city:"ISTANBUL",theme:"Last Morning",stay:"—",events:[["오전","free","이스탄불 핵심명소 후보","13:30 공항 이동을 최우선으로 두고 서로 가까운 명소 위주로 1~2곳 선택.","아야소피아|블루모스크|톱카프 궁전(시간 검토)|그랜드 바자르(운영일 확인)"],["13:30","pkg","공항 이동","여행사 차량."],["17:30","pkg","이스탄불 출발","OZ552 · 인천행."]]}];
const regionMaps=[
{title:"Golden Horn · 첫날",sub:"숙소 주변만 가볍게",loc:"ISTANBUL",pts:[["🏨","Golden City Hotel",48,48,"hotel"],["●","갈라타",61,35,"poi"],["●","카라쾨이",62,55,"poi"],["🍴","저녁 후보",70,68,"food"],["●","갈라타교",47,68,"poi"]]},
{title:"Kaleiçi · 안탈리아",sub:"도보로 이어지는 올드타운 핵심",loc:"ANTALYA",pts:[["🏨","Start Otel",33,32,"hotel"],["●","하드리아누스 문",48,42,"poi"],["●","칼레이치",55,55,"poi"],["●","구항구",44,69,"poi"],["●","흐드르륵 탑",64,72,"poi"],["🍴","저녁 후보",70,48,"food"]]},
{title:"Pamukkale · Hierapolis",sub:"투어 핵심 방문권역",loc:"PAMUKKALE",pts:[["●","히에라폴리스",48,33,"poi"],["●","파묵칼레",52,59,"poi"],["🚐","안탈리아 방향",79,76,"poi"]]},
{title:"Antalya → Cappadocia",sub:"오전 자유시간 후 국내선 이동",loc:"ANTALYA → CAPPADOCIA",pts:[["🏨","Start Otel",25,62,"hotel"],["●","칼레이치",35,48,"poi"],["✈","AYT 공항",60,65,"poi"],["✈","카파도키아",79,30,"poi"]]},
{title:"Cappadocia · Red Route",sub:"북부권 후보의 상대적 위치",loc:"CAPPADOCIA",pts:[["🏨","괴레메 숙소",48,58,"hotel"],["●","괴레메 파노라마",40,48,"poi"],["●","요정의 굴뚝",60,40,"poi"],["●","아바노스",72,25,"poi"],["●","우치히사르",25,57,"poi"],["🍴","괴레메 맛집",54,70,"food"]]},
{title:"Cappadocia · Green Route",sub:"남부권 투어의 큰 방향",loc:"CAPPADOCIA",pts:[["🏨","괴레메 숙소",55,24,"hotel"],["●","데린쿠유",58,48,"poi"],["●","으흘라라",30,68,"poi"],["●","셀리메",22,49,"poi"],["●","전망대",46,34,"poi"]]},
{title:"Historic Istanbul",sub:"두 번째 이스탄불 · 골든혼과 역사반도",loc:"ISTANBUL",pts:[["🏨","Halich Port",30,35,"hotel"],["●","스파이스 바자르",46,48,"poi"],["●","에미뇌",51,58,"poi"],["●","술탄아흐메트",68,65,"poi"],["🍴","저녁 후보",57,39,"food"]]},
{title:"Sultanahmet · 마지막 오전",sub:"공항 이동 전 1–2곳 선택",loc:"ISTANBUL",pts:[["🏨","Halich Port",25,35,"hotel"],["●","아야소피아",61,48,"poi"],["●","블루모스크",67,60,"poi"],["●","톱카프",72,37,"poi"],["●","그랜드 바자르",49,67,"poi"]]}
];
function renderDayMap(i){const d=regionMaps[i];const pts=d.pts.map(p=>`<button class="place-pin ${p[4]}" style="left:${p[2]}%;top:${p[3]}%" title="${p[1]}"><i>${p[0]}</i><b>${p[1]}</b></button>`).join("");document.getElementById("dayMap").innerHTML=`<div class="day-map-card"><div class="day-map-top"><div><small>DAY ${days[i].d} · AREA MAP</small><h3>${d.title}</h3></div><p>${d.sub}</p></div><div class="region-map"><div class="region-land"></div>${pts}<div class="map-tip">🏨 숙소 · ● 관광지 · 🍴 맛집</div><div class="locator">TÜRKİYE · NOW <b>${d.loc}</b></div></div><div class="day-map-note">※ 위치관계를 쉽게 보기 위한 간략 지도입니다. 자유일정 장소는 후보입니다.</div></div>`}
const tabs=document.getElementById('dayTabs'),content=document.getElementById('dayContent');function render(i){renderDayMap(i);[...tabs.children].forEach((x,j)=>x.classList.toggle('active',j===i));const x=days[i];const events=x.events.map(e=>{const[time,type,title,desc,cands="",rests=[]]=e;const cand=cands?`<div class="candidate">${cands.split("|").map(c=>`<span>${c}</span>`).join("")}</div>`:"";const r=rests?.length?`<div class="restaurants">${rests.map(z=>`<div class="restaurant"><a target="_blank" rel="noopener" href="${z[1]}">${z[0]} ↗</a><div class="rmeta"><span class="rating">★ ${z[2]||"평점 확인 예정"}</span><br>🍽 ${z[3]}<br>💰 ${z[4]}<br>🕐 ${z[5]}</div></div>`).join("")}</div>`:"";return `<div class="event ${type}"><div class="time">${time}</div><div class="pin"></div><div><h4>${title}</h4><p>${desc}</p>${cand}${r}</div></div>`}).join("");content.innerHTML=`<article class="day-card"><div class="day-head"><div><small>DAY ${x.d} · ${x.date}</small><h3>${x.city}</h3><p>${x.theme}</p></div><div class="stay"><small>오늘의 숙소</small><b>${x.stay}</b></div></div><div class="legend"><span><i class="dot pkg"></i>여행사 일정</span><span><i class="dot free"></i>자유 일정 · 후보</span></div><div class="timeline">${events}</div></article>`}days.forEach((x,i)=>{const b=document.createElement("button");b.className="day-tab";b.innerHTML=`<b>DAY ${x.d}</b><small>${x.date}</small>`;b.onclick=()=>render(i);tabs.appendChild(b)});render(0);const panel=document.getElementById("teamPanel"),overlay=document.getElementById("overlay");function team(o){panel.classList.toggle("open",o);overlay.classList.toggle("open",o)}document.getElementById("teamBtn").onclick=()=>team(true);document.getElementById("teamClose").onclick=()=>team(false);overlay.onclick=()=>team(false);document.getElementById("printBtn").onclick=()=>window.print();document.querySelectorAll(".map-node[data-day]").forEach(n=>n.addEventListener("click",()=>{const i=Number(n.dataset.day);render(i);document.getElementById("days").scrollIntoView({behavior:"smooth"})}));
if(!document.querySelector(".mobile-nav")){document.body.insertAdjacentHTML("beforeend",'<nav class="mobile-nav"><a href="#home"><b>⌂</b>HOME</a><a href="#days"><b>◫</b>DAYS</a><a href="#overview"><b>⌖</b>MAP</a><a href="#guide"><b>☰</b>GUIDE</a></nav>')}
const placeInfo={
"ISTANBUL":{ko:"이스탄불",en:"İstanbul",one:"두 제국의 수도였던 도시에서 비잔틴과 오스만의 시간을 한꺼번에 만나는 곳.",history:"보스포루스 해협을 사이에 둔 이스탄불은 동로마 제국의 콘스탄티노폴리스였고, 1453년 이후 오스만 제국의 수도가 됐습니다. 그래서 기독교와 이슬람, 궁전과 시장의 유산이 한 도시 안에 겹쳐 있습니다.",see:"아야소피아·블루모스크·톱카프 궁전과 골든혼·보스포루스의 지리적 관계를 함께 보면 도시가 훨씬 잘 이해됩니다.",map:"https://www.google.com/maps/search/?api=1&query=Istanbul+Turkey"},
"ANTALYA":{ko:"안탈리아",en:"Antalya",one:"지중해 휴양도시 한가운데 로마시대와 오스만시대의 흔적이 남아 있는 도시.",history:"안탈리아의 구시가지 칼레이치는 여러 시대의 성벽과 전통 가옥이 남아 있는 역사 중심지입니다. 하드리아누스 문은 로마 황제 하드리아누스의 방문을 기념해 130년에 세워졌습니다.",see:"칼레이치에서는 하드리아누스 문에서 골목을 지나 옛 항구까지 내려가는 흐름을 기억하면 좋습니다.",map:"https://www.google.com/maps/search/?api=1&query=Antalya+Turkey"},
"CAPPADOCIA":{ko:"카파도키아",en:"Cappadocia",one:"자연이 만든 기암지형을 사람들이 집·교회·도시로 바꿔 살아온 독특한 지역.",history:"카파도키아의 부드러운 화산암 지형은 오랜 침식으로 지금의 계곡과 요정의 굴뚝을 만들었습니다. 사람들은 쉽게 깎이는 암석을 파서 주거지와 예배 공간, 지하도시를 만들었습니다.",see:"풍경만 보기보다 ‘자연 지형을 사람이 어떻게 생활공간으로 활용했나’를 생각하며 보면 훨씬 흥미롭습니다.",map:"https://www.google.com/maps/search/?api=1&query=Cappadocia+Turkey"},
"PAMUKKALE":{ko:"파묵칼레",en:"Pamukkale",one:"온천수가 만든 새하얀 석회붕과 고대 온천도시가 한 장소에 겹쳐 있는 곳.",history:"칼슘이 풍부한 온천수가 흘러내리며 흰 석회질 테라스를 만들었습니다. 바로 위에는 기원전 2세기경 세워져 온천·치유 중심지로 발전한 히에라폴리스가 있습니다.",see:"자연유산인 석회붕과 도시유적인 히에라폴리스를 따로 보지 말고 ‘온천이 도시를 만들었다’는 연결로 보면 좋습니다.",map:"https://www.google.com/maps/search/?api=1&query=Pamukkale+Turkey"},
"하드리아누스 문":{en:"Hadrian's Gate",one:"약 2천 년 전 로마 황제의 방문을 기념해 만든 안탈리아 구시가지의 관문.",history:"로마 황제 하드리아누스가 이 지역을 방문한 것을 기념해 130년에 건립된 로마시대 문으로, 오늘날 칼레이치로 들어가는 대표적인 입구입니다.",see:"세 개의 아치와 장식, 그리고 현대 도시와 고대 문이 바로 맞닿아 있는 모습을 보세요.",map:"https://www.google.com/maps/search/?api=1&query=Hadrians+Gate+Antalya"},
"칼레이치":{en:"Kaleiçi",one:"성벽 안 골목에 여러 시대의 흔적이 겹쳐 있는 안탈리아의 옛 시가지.",history:"칼레이치의 성벽에는 헬레니즘·로마·비잔틴·셀주크·오스만 시대의 흔적이 이어지고, 안쪽에는 전통적인 지붕과 가옥이 남아 있습니다.",see:"골목 자체가 볼거리입니다. 하드리아누스 문에서 옛 항구 쪽으로 천천히 내려가 보세요.",map:"https://www.google.com/maps/search/?api=1&query=Kaleici+Antalya"},
"구항구":{en:"Antalya Old Harbor",one:"칼레이치 아래쪽에서 지중해와 옛 도시의 관계를 느낄 수 있는 항구.",history:"안탈리아가 지중해와 연결된 항구도시였음을 보여주는 공간으로, 오늘날에는 요트와 산책로가 어우러진 관광지입니다.",see:"위쪽 칼레이치의 성벽·가옥과 아래쪽 항구를 함께 바라보면 도시 지형이 잘 보입니다.",map:"https://www.google.com/maps/search/?api=1&query=Antalya+Old+Harbor"},
"흐드르륵 탑":{en:"Hıdırlık Tower",one:"칼레이치 남쪽 끝에서 지중해를 바라보는 로마시대 석조 탑.",history:"로마시대에 세워진 원통형 석조 구조물로, 정확한 초기 용도에는 여러 해석이 있지만 안탈리아의 오래된 해안 경관을 상징하는 유적입니다.",see:"해 질 무렵 지중해와 절벽, 탑을 함께 보는 풍경이 핵심입니다.",map:"https://www.google.com/maps/search/?api=1&query=Hidirlik+Tower+Antalya"},
"파묵칼레":{en:"Pamukkale Travertines",one:"온천수가 수천 년 동안 만들어낸 ‘목화성’ 같은 흰 석회질 테라스.",history:"탄산칼슘이 풍부한 온천수가 지표로 흐르면서 광물이 침전되어 흰색 테라스와 작은 웅덩이가 형성됐습니다. 히에라폴리스와 함께 UNESCO 세계유산입니다.",see:"흰 지형 자체뿐 아니라 위쪽 고대도시와 온천수가 어떻게 연결되는지 보세요.",map:"https://www.google.com/maps/search/?api=1&query=Pamukkale+Travertines"},
"히에라폴리스":{en:"Hierapolis",one:"온천 때문에 사람들이 모여들어 발전한 고대의 치유·휴양도시.",history:"기원전 2세기경 페르가몬의 아탈로스 왕조 시기에 세워졌고 로마시대에 번성했습니다. 극장·목욕시설·신전·네크로폴리스 등이 남아 있으며 이후 비잔틴시대에는 기독교 중심지 역할도 했습니다.",see:"시간이 짧다면 고대극장과 주요 유적을 중심으로 보고 파묵칼레와 연결해서 이해하세요.",map:"https://www.google.com/maps/search/?api=1&query=Hierapolis+Pamukkale"},
"괴레메 파노라마":{en:"Göreme Panorama",one:"카파도키아의 계곡과 암석마을을 한눈에 이해하기 좋은 전망 지점.",history:"괴레메 일대는 침식된 화산암 지형과 암굴 주거가 밀집한 카파도키아의 중심권입니다.",see:"멀리 보이는 요정의 굴뚝과 계곡, 마을이 어떤 지형 위에 놓였는지 먼저 파악하세요.",map:"https://www.google.com/maps/search/?api=1&query=Goreme+Panorama"},
"요정의 굴뚝":{en:"Fairy Chimneys",one:"화산재가 굳은 암석을 바람과 비가 깎아 만든 카파도키아의 상징.",history:"서로 다른 단단함의 암석층이 오랜 시간 침식되면서 버섯이나 기둥처럼 보이는 독특한 형태가 남았습니다.",see:"꼭대기의 단단한 암석이 아래층을 보호하면서 기둥 모양이 만들어진 모습을 찾아보세요.",map:"https://www.google.com/maps/search/?api=1&query=Fairy+Chimneys+Cappadocia"},
"아바노스":{en:"Avanos",one:"붉은 강의 점토로 만든 도자기 전통이 이어지는 카파도키아의 공예 마을.",history:"크즐으르막 강변의 점토를 활용한 도자기와 세라믹으로 유명하며, 오늘날에도 공방과 상점이 마을 곳곳에 있습니다.",see:"완성품만 보기보다 물레로 흙을 빚는 제작 과정을 보면 아바노스의 특징이 더 잘 보입니다.",map:"https://www.google.com/maps/search/?api=1&query=Avanos+Cappadocia"},
"우치히사르":{en:"Uçhisar Castle",one:"거대한 자연 암석을 파서 생활·방어 공간으로 활용한 카파도키아의 높은 전망지.",history:"우치히사르의 거대한 바위에는 방과 통로가 파여 있어 자연지형과 인간의 생활공간이 결합된 카파도키아의 특징을 잘 보여줍니다.",see:"정상부에서 괴레메와 주변 계곡이 이어지는 지형을 넓게 보는 것이 핵심입니다.",map:"https://www.google.com/maps/search/?api=1&query=Uchisar+Castle"},
"데린쿠유":{en:"Derinkuyu Underground City",one:"지상 아래 여러 층으로 이어지는 카파도키아의 거대한 지하 정착공간.",history:"부드러운 암석을 파서 거주·저장·예배 공간과 환기 시설을 만들었고, 여러 시대에 걸쳐 피난과 생활에 활용됐습니다.",see:"좁은 통로와 환기구, 방들이 어떻게 연결돼 많은 사람이 지하에서 버틸 수 있었는지 보세요.",map:"https://www.google.com/maps/search/?api=1&query=Derinkuyu+Underground+City"},
"으흘라라":{en:"Ihlara Valley",one:"깊은 협곡 안을 강과 암굴교회가 따라가는 카파도키아의 자연·역사 산책로.",history:"멜렌디즈 강이 만든 깊은 협곡으로, 계곡 벽의 부드러운 암석에는 오래전부터 교회와 생활공간이 만들어졌습니다.",see:"강변 풍경과 절벽 속 암굴 공간이 함께 나타나는 점이 다른 카파도키아 명소와의 차이입니다.",map:"https://www.google.com/maps/search/?api=1&query=Ihlara+Valley"},
"셀리메":{en:"Selime Monastery",one:"거대한 바위를 파서 교회와 생활공간을 만든 대규모 암굴 수도원.",history:"으흘라라 계곡 북쪽에 자리한 암굴 복합공간으로, 종교 공간과 생활 공간이 한 암석 지형 안에 결합돼 있습니다.",see:"외관보다 내부 공간의 규모와 여러 방이 서로 연결되는 방식을 눈여겨보세요.",map:"https://www.google.com/maps/search/?api=1&query=Selime+Monastery"},
"스파이스 바자르":{en:"Spice Bazaar · Mısır Çarşısı",one:"17세기부터 향신료와 식재료가 모여든 이스탄불의 대표 시장.",history:"뉴 모스크 복합시설의 일부로 조성된 시장으로, 향신료·차·건과일·견과류 등 식문화와 관련된 상점이 밀집해 있습니다.",see:"상품만 사기보다 시장의 색과 향, 주변 에미뇌의 상업 분위기를 함께 즐겨보세요.",map:"https://www.google.com/maps/search/?api=1&query=Spice+Bazaar+Istanbul"},
"에미뇌":{en:"Eminönü",one:"시장·트램·페리·모스크가 만나는 이스탄불 구도심의 교통과 상업 중심.",history:"골든혼 남쪽의 역사적 상업지구로 스파이스 바자르와 뉴 모스크, 선착장이 가까이 모여 있습니다.",see:"갈라타교와 골든혼, 페리, 시장을 한 프레임으로 보면 이스탄불의 일상적인 활기가 잘 느껴집니다.",map:"https://www.google.com/maps/search/?api=1&query=Eminonu+Istanbul"},
"술탄아흐메트":{en:"Sultanahmet",one:"아야소피아와 블루모스크가 마주 보는 이스탄불 역사여행의 중심.",history:"동로마 제국과 오스만 제국의 핵심 건축물이 매우 가까운 거리에 모여 있어 두 시대의 수도 역사를 비교하기 좋은 지역입니다.",see:"광장 한가운데에서 아야소피아와 블루모스크를 번갈아 보며 두 건축물의 시대와 역할을 비교해보세요.",map:"https://www.google.com/maps/search/?api=1&query=Sultanahmet+Istanbul"},
"아야소피아":{en:"Hagia Sophia · Ayasofya",one:"비잔틴 대성당에서 오스만 모스크로, 이스탄불의 역사 변화가 한 건물에 겹쳐진 곳.",history:"6세기 유스티니아누스 1세 시대에 세워진 동로마 제국의 대표 성당입니다. 1453년 오스만 정복 뒤 모스크가 되었고, 20세기에는 박물관을 거쳐 2020년 다시 모스크로 사용되고 있습니다.",see:"거대한 돔과 기독교 모자이크, 이슬람 서예와 미나레트가 한 공간에 공존하는 점이 핵심입니다.",map:"https://www.google.com/maps/search/?api=1&query=Hagia+Sophia+Istanbul"},
"블루모스크":{en:"Sultan Ahmed Mosque",one:"푸른 이즈니크 타일과 여섯 개의 미나레트로 유명한 17세기 오스만 모스크.",history:"술탄 아흐메트 1세 시대에 지어진 제국 모스크로, 아야소피아 맞은편에서 오스만 건축의 상징적인 스카이라인을 만듭니다.",see:"중앙 돔과 연속되는 작은 돔, 내부의 푸른 계열 타일, 여섯 미나레트를 함께 보세요.",map:"https://www.google.com/maps/search/?api=1&query=Blue+Mosque+Istanbul"},
"톱카프":{en:"Topkapı Palace",one:"오스만 술탄들이 제국을 통치하고 생활했던 궁전.",history:"15세기 이후 오랫동안 오스만 제국의 행정과 왕실 생활의 중심이었습니다. 여러 안뜰과 관청·보물·왕실 공간이 이어지는 구조입니다.",see:"단순한 왕의 집이 아니라 ‘제국의 정부청사 + 왕실 공간’이었다고 생각하면 구조가 이해됩니다.",map:"https://www.google.com/maps/search/?api=1&query=Topkapi+Palace"},
"그랜드 바자르":{en:"Grand Bazaar · Kapalıçarşı",one:"수백 년 동안 상업이 이어져온 거대한 실내 시장.",history:"오스만시대부터 발전해온 이스탄불의 대표적인 상업공간으로, 오늘날에도 보석·카펫·가죽·도자기·기념품 상점이 복잡한 골목을 채웁니다.",see:"무엇을 살지보다 시장의 골목 구조와 상점 간판, 흥정 문화를 경험하는 것도 재미입니다.",map:"https://www.google.com/maps/search/?api=1&query=Grand+Bazaar+Istanbul"}
};
function normalizePlace(t){t=(t||"").trim();if(t.includes("히에라폴리스"))return "히에라폴리스";if(t.includes("파묵칼레"))return "파묵칼레";if(t.includes("우치히사르"))return "우치히사르";if(t.includes("데린쿠유"))return "데린쿠유";if(t.includes("으흘라라"))return "으흘라라";if(t.includes("셀리메"))return "셀리메";if(t.includes("톱카프"))return "톱카프";if(t.includes("그랜드 바자르"))return "그랜드 바자르";return t}
function openPlace(key){key=normalizePlace(key);const p=placeInfo[key];if(!p)return;const body=document.getElementById("placeSheetBody");body.innerHTML=`<div class="place-kicker">1-MINUTE PLACE GUIDE</div><h2>${p.ko||key}</h2><div class="en">${p.en||""}</div><div class="one-line">${p.one}</div><div class="place-info"><h4>30초 역사</h4><p>${p.history}</p></div><div class="place-info"><h4>여기서는 이것만 보자</h4><p>${p.see}</p></div><a class="place-map-link" href="${p.map}" target="_blank" rel="noopener">📍 Google Maps에서 보기 ↗</a><small class="place-source">현재 후보 기준 기본 설명 · 일정 확정 후 최종 보완 예정</small>`;document.getElementById("placeOverlay").classList.add("open");document.getElementById("placeSheet").classList.add("open");document.getElementById("placeSheet").setAttribute("aria-hidden","false")}
function closePlace(){document.getElementById("placeOverlay").classList.remove("open");document.getElementById("placeSheet").classList.remove("open");document.getElementById("placeSheet").setAttribute("aria-hidden","true")}
document.addEventListener("click",e=>{const el=e.target.closest(".place-link");if(el){e.preventDefault();openPlace(el.dataset.place||el.textContent)}});
document.getElementById("placeClose")?.addEventListener("click",closePlace);document.getElementById("placeOverlay")?.addEventListener("click",closePlace);
const oldRender=render;render=function(i){oldRender(i);document.querySelectorAll(".candidate span").forEach(el=>{const k=normalizePlace(el.textContent);if(placeInfo[k]){el.classList.add("place-link");el.dataset.place=k}});document.querySelectorAll(".place-pin").forEach(el=>{const k=normalizePlace(el.title);if(placeInfo[k]){el.classList.add("place-link");el.dataset.place=k}});const ch=document.querySelector(".day-head h3");if(ch){const raw=ch.textContent.trim();const keys=raw.split("→").map(x=>x.trim());const key=keys.find(x=>placeInfo[x]);if(key){ch.classList.add("city-place","place-link");ch.dataset.place=key}}}
render(0);
